permalink: /articles/:year/:title.html
highlighter: rouge
markdown: kramdown
title: "Superloopy.io blog posts"
author: Stig Brautaset
feed:
  path: atom.xml
gems:
  - jekyll-redirect-from
  - jekyll-feed

whitelist:
  - jekyll-redirect-from
  - jekyll-feed
