permalink: /articles/:year/:title.html
highlighter: rouge
markdown: kramdown
feed:
  path: atom.xml
gems:
  - jekyll-redirect-from
  - jekyll-feed

whitelist:
  - jekyll-redirect-from
  - jekyll-feed
