version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.11

executors:
  emacs27:
    working_directory: ~/blog
    docker:
      - image: silex/emacs:27.2-ci
  python3:
    docker:
      - image: circleci/python:3.7

jobs:
  build:
    executor: emacs27
    steps:
      - checkout
      - restore_cache:
          keys:
            - v6-org-{{ .Branch }}
            - v6-org-trunk
      - run: sleep 300
      - run:
          name: Tangle CSS
          command: >
            emacs --batch
            --eval "(require 'ob-tangle)"
            --eval '(org-babel-tangle-file "style.org")'
      - run:
          name: Publish Blog
          command: |
            emacs --batch --load deps.el --load publish.el --eval '(org-publish-all t)'
      - store_artifacts:
          path: ~/blog/_site
          destination: html
      - save_cache:
          key: v6-org-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/.emacs.d
      - persist_to_workspace:
          root: ~/blog
          paths:
            - '_site'

  deploy:
    executor: python3
    steps:
      - attach_workspace:
          at: ~/blog
      - aws-s3/sync:
          from: ~/blog/_site
          to: 's3://www.brautaset.org'
          arguments: >-
            --delete
            --acl public-read
            --cache-control "max-age=86400"
      - run: >-
          aws cloudfront create-invalidation
          --distribution-id E2HQ2C8QF1FXUZ
          --paths '/*'

workflows:
  version: 2

  pr:
    jobs:
      - build:
          filters:
            branches:
              ignore: trunk

  deploy:
    jobs:
      - build:
          filters:
            branches:
              only: trunk
      - deploy:
          requires:
            - build
